"""add bot and testing models

Revision ID: ec63f613a086
Revises: a1b2c3d4e5f6
Create Date: 2026-05-19 22:53:11.734522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec63f613a086'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botusers',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_botusers'))
    )
    op.create_index(op.f('ix_botusers_id'), 'botusers', ['id'], unique=False)
    op.create_index(op.f('ix_botusers_telegram_id'), 'botusers', ['telegram_id'], unique=True)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('tgadmins',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tgadmins'))
    )
    op.create_index(op.f('ix_tgadmins_id'), 'tgadmins', ['id'], unique=False)
    op.create_index(op.f('ix_tgadmins_is_active'), 'tgadmins', ['is_active'], unique=False)
    op.create_index(op.f('ix_tgadmins_telegram_id'), 'tgadmins', ['telegram_id'], unique=True)
    op.create_table('questions',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_questions_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_is_active'), 'questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_table('answeroptions',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answeroptions_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answeroptions'))
    )
    op.create_index(op.f('ix_answeroptions_id'), 'answeroptions', ['id'], unique=False)
    op.create_index(op.f('ix_answeroptions_question_id'), 'answeroptions', ['question_id'], unique=False)
    op.create_table('testattempts',
    sa.Column('bot_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_option_id', sa.BigInteger(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_user_id'], ['botusers.id'], name=op.f('fk_testattempts_bot_user_id_botusers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_testattempts_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['answeroptions.id'], name=op.f('fk_testattempts_selected_option_id_answeroptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_testattempts_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testattempts'))
    )
    op.create_index(op.f('ix_testattempts_bot_user_id'), 'testattempts', ['bot_user_id'], unique=False)
    op.create_index(op.f('ix_testattempts_id'), 'testattempts', ['id'], unique=False)
    op.create_index(op.f('ix_testattempts_is_correct'), 'testattempts', ['is_correct'], unique=False)
    op.create_index(op.f('ix_testattempts_question_id'), 'testattempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_testattempts_subject_id'), 'testattempts', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testattempts_subject_id'), table_name='testattempts')
    op.drop_index(op.f('ix_testattempts_question_id'), table_name='testattempts')
    op.drop_index(op.f('ix_testattempts_is_correct'), table_name='testattempts')
    op.drop_index(op.f('ix_testattempts_id'), table_name='testattempts')
    op.drop_index(op.f('ix_testattempts_bot_user_id'), table_name='testattempts')
    op.drop_table('testattempts')
    op.drop_index(op.f('ix_answeroptions_question_id'), table_name='answeroptions')
    op.drop_index(op.f('ix_answeroptions_id'), table_name='answeroptions')
    op.drop_table('answeroptions')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_active'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_tgadmins_telegram_id'), table_name='tgadmins')
    op.drop_index(op.f('ix_tgadmins_is_active'), table_name='tgadmins')
    op.drop_index(op.f('ix_tgadmins_id'), table_name='tgadmins')
    op.drop_table('tgadmins')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_botusers_telegram_id'), table_name='botusers')
    op.drop_index(op.f('ix_botusers_id'), table_name='botusers')
    op.drop_table('botusers')
    # ### end Alembic commands ###
