"""init auth

Revision ID: fccf32296319
Revises: 
Create Date: 2026-01-29 23:38:18.596817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccf32296319'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminusers',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hashed', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adminusers'))
    )
    op.create_index(op.f('ix_adminusers_id'), 'adminusers', ['id'], unique=False)
    op.create_index(op.f('ix_adminusers_username'), 'adminusers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adminusers_username'), table_name='adminusers')
    op.drop_index(op.f('ix_adminusers_id'), table_name='adminusers')
    op.drop_table('adminusers')
    # ### end Alembic commands ###
