"""attempt session round_number

Revision ID: ec4d1ee433fa
Revises: fc673e116f9b
Create Date: 2026-05-20 00:37:24.750381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4d1ee433fa'
down_revision: Union[str, Sequence[str], None] = 'fc673e116f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'attemptsessions',
        sa.Column('round_number', sa.Integer(), nullable=False, server_default='1'),
    )
    op.create_index(op.f('ix_attemptsessions_round_number'), 'attemptsessions', ['round_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attemptsessions_round_number'), table_name='attemptsessions')
    op.drop_column('attemptsessions', 'round_number')
    # ### end Alembic commands ###
