"""uz: student_id, subject attempts, attempt sessions

Revision ID: 09266905882c
Revises: ec63f613a086
Create Date: 2026-05-20 00:16:57.351435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09266905882c'
down_revision: Union[str, Sequence[str], None] = 'ec63f613a086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attemptsessions',
    sa.Column('bot_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_user_id'], ['botusers.id'], name=op.f('fk_attemptsessions_bot_user_id_botusers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_attemptsessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attemptsessions'))
    )
    op.create_index(op.f('ix_attemptsessions_bot_user_id'), 'attemptsessions', ['bot_user_id'], unique=False)
    op.create_index(op.f('ix_attemptsessions_id'), 'attemptsessions', ['id'], unique=False)
    op.create_index(op.f('ix_attemptsessions_status'), 'attemptsessions', ['status'], unique=False)
    op.create_index(op.f('ix_attemptsessions_subject_id'), 'attemptsessions', ['subject_id'], unique=False)
    op.add_column('botusers', sa.Column('student_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_botusers_student_id'), 'botusers', ['student_id'], unique=True)
    op.drop_column('botusers', 'last_name')
    op.drop_column('botusers', 'first_name')
    op.add_column('subjects', sa.Column('questions_per_attempt', sa.Integer(), server_default='25', nullable=False))
    op.add_column('subjects', sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False))
    op.add_column('testattempts', sa.Column('attempt_session_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_testattempts_attempt_session_id'), 'testattempts', ['attempt_session_id'], unique=False)
    op.create_foreign_key(op.f('fk_testattempts_attempt_session_id_attemptsessions'), 'testattempts', 'attemptsessions', ['attempt_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_testattempts_attempt_session_id_attemptsessions'), 'testattempts', type_='foreignkey')
    op.drop_index(op.f('ix_testattempts_attempt_session_id'), table_name='testattempts')
    op.drop_column('testattempts', 'attempt_session_id')
    op.drop_column('subjects', 'max_attempts')
    op.drop_column('subjects', 'questions_per_attempt')
    op.add_column('botusers', sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('botusers', sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_botusers_student_id'), table_name='botusers')
    op.drop_column('botusers', 'student_id')
    op.drop_index(op.f('ix_attemptsessions_subject_id'), table_name='attemptsessions')
    op.drop_index(op.f('ix_attemptsessions_status'), table_name='attemptsessions')
    op.drop_index(op.f('ix_attemptsessions_id'), table_name='attemptsessions')
    op.drop_index(op.f('ix_attemptsessions_bot_user_id'), table_name='attemptsessions')
    op.drop_table('attemptsessions')
    # ### end Alembic commands ###
