"""add is_active column

Revision ID: 13519c1d1dc9
Revises: 385c7ea559be
Create Date: 2026-01-30 02:34:36.842678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13519c1d1dc9'
down_revision: Union[str, Sequence[str], None] = '385c7ea559be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminusers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_adminusers_is_active'), 'adminusers', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adminusers_is_active'), table_name='adminusers')
    op.drop_column('adminusers', 'is_active')
    # ### end Alembic commands ###
